### ISSUE TITLE
LinkedIn ?

### ISSUE THREAD

**Issue by pcout** [cshold/social-sharing-buttons#1]
Hello,

Can you add the LinkedIn button ?

Thanks

**Comment by jaredatch** [comment]
Agreed

**Comment by revxx14** [comment]
Been a while since you guys requested LinkedIn, but I've added it to [my fork](https://github.com/revxx14/social-sharing-buttons). I've submitted a pull request, not sure how active the developer of this project is.

**Comment by cshold** [comment]
Have a sour taste in mouth from this project because I inadvertently became Twittter-famous in Egypt after a few news sites (or bot-sites, can't tell) didn't remove the `via cshold` from the links when they used them. Alas, the PR looks great and I'll merge it in. Thanks @revxx14

**Comment by revxx14** [comment]
Glad to do it, this is a great little project :)
