### ISSUE TITLE
Mobile/Responsiveness

### ISSUE THREAD

**Issue by angelcosta** [cshold/social-sharing-buttons#10]
How could I go about optimizing it for mobile view?

**Comment by cshold** [comment]
How do you mean? The buttons open external links so we can't control what appears there. The share buttons themselves are just `inline-block` elements so will wrap depending on the space available. Any further styling you would like should be done on a per-project basis.

**Comment by angelcosta** [comment]
I think it's the jquery that makes all the counts go to zero in mobile.
I'll work on that. Thanks.
