### ISSUE TITLE
Twitter to shut down JSON endpoint that enables share counts

### ISSUE THREAD

**Issue by pagelab** [cshold/social-sharing-buttons#14]
https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform

This will happen November 20, and looks like there's no other usable alternative for this.

Would be nice at least to have a caching system to hold the actual count. Is this possible?

**Comment by revxx14** [comment]
I just read about this the other day and I was about to log the same issue. I'm not the main developer on this, but I have contributed a few things recently (Skype, Reddit, LinkedIn).

I could be wrong, but I think storing the number of shares server side is a bit out of scope for this project. Right now, it's all just using JSON callbacks to get share numbers where possible, and just not displaying any share number if not possible via JSON. This script is really just a lightweight, easy to install sharing script, and I think incorporating some kind of server-side code would dimension 

I do wish that Twitter wouldn't have made this decision, seems like a really shortsighted move. Hopefully they'll reverse it. Until then, I'll submit a pull request removing the tweet counter.

**Comment by pagelab** [comment]
There's a free alternative to retrieve the Twitter share count: www.opensharecount.com It's not official though.

**Comment by revxx14** [comment]
Very interesting, worth looking in to. Thanks!

**Comment by cshold** [comment]
Removed share counts from the plugin since they're not officially supported anymore
