### ISSUE TITLE
New Error for Linkedin

### ISSUE THREAD

**Issue by suture** [cshold/social-sharing-buttons#19]
There's a new console error showing up for Linked in. 

> Failed to load resource: the server responded with a status of 400 (Bad Request)

I think the error wasn't happening last week. Maybe something changed at Linkedin?

You can see it also on the demo page
http://labs.carsonshold.com/social-sharing-buttons/

![error](https://cloud.githubusercontent.com/assets/90376/15273775/e4c7f154-1add-11e6-905b-b8054d40b441.jpg)

**Comment by suture** [comment]
many thanks. btw the demo page is still display console errors. 
re: http://labs.carsonshold.com/social-sharing-buttons/

**Comment by cshold** [comment]
The same errors? Might be a caching issue — CloudFlare has been driving me nuts on my `labs` pages.

**Comment by suture** [comment]
It looks good now.
