### ISSUE TITLE
Pinterest pins are not returned

### ISSUE THREAD

**Issue by Chirica-Mugurel** [cshold/social-sharing-buttons#4]
When i use $obj->get_pinterest(); to display the pins from a specific page i get no return.

I checked my url to see if there are any pins with this link http://api.pinterest.com/v1/urls/count.json?url=the_url and i see the number of pins.

**Comment by cshold** [comment]
Not sure what you mean. I don't have an API setup for this plugin so there's no way to get only the number from an external JS call, which isn't the point of it. Let me know if I'm missing something.
