### ISSUE TITLE
Page Cannot be displayed Issue

### ISSUE THREAD

**Issue by akj2784** [cshold/social-sharing-buttons#7]
Hi Team,
I have a page wherein I have placed my code to share it on facebook. But when I click on the link, it opens up the new window but the error says Page cannot be displayed. 
And when I add / at the end of the URL, it shows me the correct link on the new window but when I open the page from that window, it screws up my layout as it is not able to find the correct path for CSS and images.

Any help would be appreciated.

Regards,
Akash

**Comment by cshold** [comment]
Do you have a demo of this you can show?

**Comment by akj2784** [comment]
Hi,
Thanks for the quick response.
Please check the following link
http://www.importantbankingnews.com/HTML/BankingNews/Recovery-Of-Bad-Loans-May-Only-Help-India-In-Growth.php

When I try to share the same page, the path comes up correctly on the new window of facebook share. But try and open the page from that window, the layout is screwed up.

**Comment by akj2784** [comment]
And this is the code I have used for Facebook.
<div class="social-sharing" >

    
    <a target="_blank" href="http://www.facebook.com/sharer.php?u=http://www.importantbankingnews.com/HTML/BankingNews/Recovery-Of-Bad-Loans-May-Only-Help-India-In-Growth.php/" class="share-facebook">
      <span class="icon icon-facebook" aria-hidden="true"></span>
      <span class="share-title">Share</span>
      <span class="share-count">0</span>
    </a>
</div>

**Comment by akj2784** [comment]
<a target="_blank" href="http://www.facebook.com/sharer.php?u=http://www.importantbankingnews.com/HTML/BankingNews/Recovery-Of-Bad-Loans-May-Only-Help-India-In-Growth.php/" class="share-facebook">

**Comment by cshold** [comment]
This isn't an issue with the share plugin unfortunately. Using [Facebook's linter](https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fwww.importantbankingnews.com%2FHTML%2FBankingNews%2FRecovery-Of-Bad-Loans-May-Only-Help-India-In-Growth.php) it shows the URL without the trailing slash returns a bad HTTP response code. I'm not sure why the URL is broken, but it'll be something on your site or server that's causing the issue.

Good hunting.

**Comment by akj2784** [comment]
ok. Thank you.
